import { render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { beforeEach, describe, expect, it, vi } from "vitest";
import App from "../App";
import { MOCK_HEALTH, MOCK_INVOICES } from "../api/mock";
import type { InvoicePage, InvoiceQuery } from "../api/types";

// Only the network layer is faked; the hook, table, pager and filters all run for real.
vi.mock("../api/client", async () => {
  const actual = await vi.importActual<typeof import("../api/client")>("../api/client");
  return { ...actual, getHealth: vi.fn(), listInvoices: vi.fn() };
});

const { getHealth, listInvoices } = await import("../api/client");

/** 32 stored rows, enough for two pages at the default page size. */
const ALL_ROWS = Array.from({ length: 32 }, (_, index) => ({
  ...MOCK_INVOICES[index % MOCK_INVOICES.length],
  id: 1000 + index,
  invoice_number: `INV-${1000 + index}`,
}));

function pageOf(query: InvoiceQuery): InvoicePage {
  const page = query.page ?? 1;
  const pageSize = query.page_size ?? 25;
  const start = (page - 1) * pageSize;
  return {
    items: ALL_ROWS.slice(start, start + pageSize),
    total: ALL_ROWS.length,
    page,
    page_size: pageSize,
  };
}

function lastQuery(): InvoiceQuery {
  return vi.mocked(listInvoices).mock.calls.at(-1)?.[0] ?? {};
}

describe("App", () => {
  beforeEach(() => {
    vi.mocked(getHealth).mockReset();
    vi.mocked(getHealth).mockResolvedValue({ ...MOCK_HEALTH, database: "postgres" });
    vi.mocked(listInvoices).mockReset();
    vi.mocked(listInvoices).mockImplementation((query = {}) => Promise.resolve(pageOf(query)));
  });

  it("keeps only the database in the header chip and puts the model on the composer", async () => {
    render(<App />);

    expect(await screen.findByText("Postgres")).toBeInTheDocument();
    expect(screen.queryByText(/Claude: ready/)).not.toBeInTheDocument();
    expect(await screen.findByText("claude-sonnet-5")).toBeInTheDocument();
    expect(
      screen.getByTitle("Answers are generated by Claude Sonnet through LangChain"),
    ).toBeInTheDocument();
  });

  it("says the key is missing on the composer when the server has none", async () => {
    vi.mocked(getHealth).mockResolvedValue({ ...MOCK_HEALTH, llm_configured: false });
    render(<App />);

    expect(await screen.findByText("Claude: key missing")).toBeInTheDocument();
    expect(screen.queryByText("claude-sonnet-5")).not.toBeInTheDocument();
  });

  it("pages through the list and reports the visible range", async () => {
    const user = userEvent.setup();
    render(<App />);

    expect(await screen.findByText("1-25 of 32")).toBeInTheDocument();
    expect(screen.getByRole("button", { name: "Previous" })).toBeDisabled();

    await user.click(screen.getByRole("button", { name: "Next" }));

    expect(await screen.findByText("26-32 of 32")).toBeInTheDocument();
    expect(lastQuery()).toMatchObject({ page: 2, page_size: 25 });
    expect(screen.getByRole("button", { name: "Next" })).toBeDisabled();
  });

  it("returns to page 1 when a filter changes", async () => {
    const user = userEvent.setup();
    render(<App />);

    await screen.findByText("1-25 of 32");
    await user.click(screen.getByRole("button", { name: "Next" }));
    await screen.findByText("26-32 of 32");

    await user.selectOptions(screen.getByLabelText("Status"), "overdue");
    await waitFor(() => expect(lastQuery()).toMatchObject({ page: 1, status: "overdue" }));

    await user.click(screen.getByRole("button", { name: "Next" }));
    await user.type(screen.getByLabelText("Search"), "northwind");
    await waitFor(() => expect(lastQuery()).toMatchObject({ page: 1, q: "northwind" }));
  });
});
